apiVersion: v1
kind: Namespace
metadata:
    name: beta
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
  namespace: beta
spec:
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: paswrd
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: beta
spec:
  selector:
    name: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: beta
data:
    DB_Host: bXlzcWw=
    DB_User: cm9vdA==
    DB_Password: cGFzd3Jk
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-mysql
  labels:
    app: example-app
    name: simple-webapp-mysql
  namespace: beta
spec:
  containers:
  - name: simple-webapp-mysql
    image: kodekloud/simple-webapp-mysql
    env:
    - name: DB_Host
      value: "mysql-service"
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: app-secret-volumes
      mountPath: "/opt/app-secret-volumes"
      readOnly: true
    envFrom:
      - secretRef:
          name: app-secret
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-service
  namespace: beta
spec:
  selector:
    name: simple-webapp-mysql
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
