apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    system: first
spec:
  containers:
  - name: simple-webapp-color
    image: mmumshad/simple-webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red

